openapi: 3.1.0
info:
  title: cpr-contracts
  version: 0.0.0
  description: Canonical models for Climate Policy Radar. Versioned by git tag, not info.version.
paths: {}
components:
  schemas:
    BaseDocument:
      properties:
        id:
          title: Id
          type: string
        title:
          title: Title
          type: string
        description:
          anyOf:
            - type: string
            - type: 'null'
          default: null
          title: Description
        items:
          default: []
          items:
            $ref: '#/components/schemas/Item'
          title: Items
          type: array
        attributes:
          additionalProperties:
            anyOf:
              - type: string
              - type: number
              - type: boolean
          default: {}
          title: Attributes
          type: object
      required:
        - id
        - title
      title: BaseDocument
      type: object
    BaseLabel:
      properties:
        id:
          title: Id
          type: string
        type:
          title: Type
          type: string
        value:
          title: Value
          type: string
        attributes:
          additionalProperties:
            anyOf:
              - type: string
              - type: number
              - type: boolean
          default: {}
          title: Attributes
          type: object
      required:
        - id
        - type
        - value
      title: BaseLabel
      type: object
    Document:
      properties:
        id:
          title: Id
          type: string
        title:
          title: Title
          type: string
        description:
          anyOf:
            - type: string
            - type: 'null'
          default: null
          title: Description
        items:
          default: []
          items:
            $ref: '#/components/schemas/Item'
          title: Items
          type: array
        attributes:
          additionalProperties:
            anyOf:
              - type: string
              - type: number
              - type: boolean
          default: {}
          title: Attributes
          type: object
        labels:
          items:
            $ref: '#/components/schemas/LabelRelationship'
          title: Labels
          type: array
        documents:
          items:
            $ref: '#/components/schemas/DocumentRelationship'
          title: Documents
          type: array
      required:
        - id
        - title
        - labels
        - documents
      title: Document
      type: object
    DocumentRelationship:
      properties:
        type:
          title: Type
          type: string
        value:
          $ref: '#/components/schemas/DocumentWithoutDocumentRelationships'
        timestamp:
          anyOf:
            - format: date-time
              type: string
            - type: 'null'
          default: null
          title: Timestamp
      required:
        - type
        - value
      title: DocumentRelationship
      type: object
    DocumentWithoutDocumentRelationships:
      properties:
        id:
          title: Id
          type: string
        title:
          title: Title
          type: string
        description:
          anyOf:
            - type: string
            - type: 'null'
          default: null
          title: Description
        items:
          default: []
          items:
            $ref: '#/components/schemas/Item'
          title: Items
          type: array
        attributes:
          additionalProperties:
            anyOf:
              - type: string
              - type: number
              - type: boolean
          default: {}
          title: Attributes
          type: object
        labels:
          default: []
          items:
            $ref: '#/components/schemas/LabelRelationship'
          title: Labels
          type: array
      required:
        - id
        - title
      title: DocumentWithoutDocumentRelationships
      type: object
    Item:
      properties:
        url:
          anyOf:
            - type: string
            - type: 'null'
          default: null
          title: Url
        type:
          title: Type
          type: string
        content_type:
          anyOf:
            - type: string
            - type: 'null'
          default: null
          title: Content Type
      required:
        - type
      title: Item
      type: object
    Label:
      properties:
        id:
          title: Id
          type: string
        type:
          title: Type
          type: string
        value:
          title: Value
          type: string
        attributes:
          additionalProperties:
            anyOf:
              - type: string
              - type: number
              - type: boolean
          default: {}
          title: Attributes
          type: object
        labels:
          items:
            $ref: '#/components/schemas/LabelRelationship'
          title: Labels
          type: array
      required:
        - id
        - type
        - value
        - labels
      title: Label
      type: object
    LabelRelationship:
      properties:
        type:
          title: Type
          type: string
        value:
          $ref: '#/components/schemas/LabelWithoutLabelRelationships'
        timestamp:
          anyOf:
            - format: date-time
              type: string
            - type: 'null'
          default: null
          title: Timestamp
      required:
        - type
        - value
      title: LabelRelationship
      type: object
    LabelWithoutLabelRelationships:
      properties:
        id:
          title: Id
          type: string
        type:
          title: Type
          type: string
        value:
          title: Value
          type: string
        attributes:
          additionalProperties:
            anyOf:
              - type: string
              - type: number
              - type: boolean
          default: {}
          title: Attributes
          type: object
      required:
        - id
        - type
        - value
      title: LabelWithoutLabelRelationships
      type: object
